/* 

Question 1: DSA Given an array of integers, return the length of the longest increasing subsequence.
A subsequence is a sequence that can be derived from the array by deleting some or no elements
without changing the order of the remaining elements. For example, given the array [10, 9, 2, 5, 3, 7,
101, 18], the longest increasing subsequence is [2, 3, 7, 101], and its length is 4.

*/

function longestSubsequence(nums) {
    if (nums.length === 0) return 0;

    let dp = [];

    for (let num of nums) {
        if (dp.length === 0 || num > dp[dp.length - 1]) {
            dp.push(num);
        } else {
            let left = 0, right = dp.length - 1;
            while (left < right) {
                let mid = Math.floor((left + right) / 2);
                if (dp[mid] < num) {
                    left = mid + 1;
                } else {
                    right = mid;
                }
            }
            dp[right] = num;
        }
    }
    // return dp;
    return dp.length;
}

console.log(longestSubsequence([10, 9, 2, 5, 3, 7, 101, 18]));





/* 

Question 2: DSA Given an array of integers nums and an integer target, return the indices of the two
numbers such that they add up to target. You may assume that each input would have exactly one
solution, and you may not use the same element twice. You can return the answer in any order.
For example, given:
const nums = [2, 7, 11, 15];
const target = 9;
The function should return [0, 1] because nums[0] + nums[1] = 2 + 7 = 9.
Requirements:
--> Implement the solution in JavaScript.
--> The solution should have a time complexity better than O(n^2).
--> Include proper error handling for edge cases.
*/


function twoSum(nums, target) {
    if (!Array.isArray(nums)) {
        throw new TypeError("First argument must be an array.");
    }

    if (typeof target !== "number") {
        throw new TypeError("Target must be a number.");
    }

    const seen = new Map();

    for (let i = 0; i < nums.length; i++) {
        const complement = target - nums[i];

        if (seen.has(complement)) {
            return [seen.get(complement), i];
        }

        seen.set(nums[i], i);
    }

    throw new Error("No two sum solution found.");
}

console.log(twoSum([2, 7, 11, 15], 9))

/*
Your task is to write an aggregation pipeline to calculate the total revenue generated by each store
for each month, along with the average price of items sold. The result should be sorted first by store
and then by month (in ascending order).
*/

db.sales.aggregate([
    {
        $unwind: "$items"
    },

    {
        $addFields: {
            itemRevenue: { $multiply: ["$items.quantity", "$items.price"] },
            month: { $dateToString: { format: "%Y-%m", date: "$date" } }
        }
    },

    {
        $group: {
            _id: {
                store: "$store",
                month: "$month"
            },
            totalRevenue: { $sum: "$itemRevenue" },
            averagePrice: { $avg: "$items.price" }
        }
    },

    {
        $project: {
            _id: 0,
            store: "$_id.store",
            month: "$_id.month",
            totalRevenue: 1,
            averagePrice: 1
        }
    },

    {
        $sort: {
            store: 1,
            month: 1
        }
    }
]);


